### PR TITLE
fix GotoFile

### PR DESCRIPTION
**Pull request by d12frosted**
Just to have things working :D

### CODE REVIEW

**Comment by nosami** [comment]
eek! thanks!

Not sure anyone would ever use this though. Pretty sure every editor has this feature :)

**Comment by d12frosted** [comment]
> eek! thanks!

You're welcome :D

> Not sure anyone would ever use this though. Pretty sure every editor has this feature :)

Hm. Probably I am missing something. Always using this feature from emacs :D It's pretty slow at the first call, but anyway, really useful. Know any good alternatives for emacs?

**Comment by nosami** [comment]
I use helm-projectile mostly.... or you can use ido or something :)

**Comment by d12frosted** [comment]
Thanks, I'll give it a try :)

**Pull request merged**
